[dependencies]
base = "0.10.4"
map = "9.0.1"
swb = "https://github.com/infu/swb"
sha2 = "0.0.4"

vector = "0.3.1"
rep-indy-hash = "0.1.1"

stable-write-only = "https://github.com/skilesare/StableWriteOnly.mo#v0.1.0@02e9aac74bdbed86b52ebed985d82b6ef66a76d8"

map9 = "https://github.com/ZhenyaUsenko/motoko-hash-map#v9.0.1@10b68f6ea8df5e72dfa4c07a50c8bb60a916c233"

[dev-dependencies]
itertools = "0.2.1"


